site_name: file2stix Docs
markdown_extensions:
  - admonition
theme:
  name: material
  features:
    - navigation.instant
nav:
  - 1. Index: index.md
  - 2. Inputs: inputs.md
  - 3. Extraction Modes:
      - 3.1. Overview: extractions.md
      - 3.2. Analysis Mode (default): extractions-analysis-mode.md
      - 3.3. Observed Mode: extractions-observed-mode.md
      - 3.4. Sightings Mode: extractions-sightings-mode.md
  - 4. Backends: backends.md
  - 5. Developers / Testing: developers.md
docs_dir: docs/
extra:
  generator: false
  version:
    provider: mike
repo_url: https://github.com/signalscorps/file2stix
repo_name: signalscorps/file2stix
edit_uri: edit/main/docs/
copyright: Copyright &copy; Signals Corps

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.signalscorps.com/
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/signalscorps-public/shared_invite/zt-1exnc12ww-9RKR6aMgO57GmHcl156DAA
    - icon: fontawesome/brands/github
      link: https://github.com/signalscorps